use_frameworks!

platform :ios, '9.0'

target 'TFMultiFileUploader_Example' do
  pod 'TFMultiFileUploader', :path => '../'

  target 'TFMultiFileUploader_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
